-- MySQL Script generated by MySQL Workbench
-- Mon Jun 15 09:23:45 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
-- Officieel groeps-schema (WhatsApp). init.sql voegt extra Kerem-kolommen toe voor wagenpark.

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

DROP SCHEMA IF EXISTS `Eend` ;

CREATE SCHEMA IF NOT EXISTS `Eend` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `Eend` ;

DROP TABLE IF EXISTS `Eend`.`Autos` ;

CREATE TABLE IF NOT EXISTS `Eend`.`Autos` (
  `autoID` INT(11) NOT NULL AUTO_INCREMENT,
  `merk` VARCHAR(50) NOT NULL,
  `type` VARCHAR(100) NOT NULL,
  `kenteken` VARCHAR(15) NOT NULL,
  `transmissie` ENUM('schakel', 'automaat') NOT NULL,
  PRIMARY KEY (`autoID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

DROP TABLE IF EXISTS `Eend`.`instructeurs` ;

CREATE TABLE IF NOT EXISTS `Eend`.`instructeurs` (
  `instructeurID` INT(11) NOT NULL AUTO_INCREMENT,
  `voornaam` VARCHAR(50) NOT NULL,
  `tussenvoegsel` VARCHAR(30) NULL DEFAULT NULL,
  `achternaam` VARCHAR(100) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `wachtwoord` VARCHAR(255) NOT NULL,
  `telefoon` VARCHAR(20) NOT NULL,
  `omschrijving` VARCHAR(255) NULL DEFAULT NULL,
  `transmissie` ENUM('schakel', 'automaat', 'beide') NOT NULL DEFAULT 'beide',
  `rol` ENUM('admin', 'instructeur') NOT NULL DEFAULT 'instructeur',
  `afwezigheid` ENUM('beschikbaar', 'niet') NOT NULL DEFAULT 'beschikbaar',
  PRIMARY KEY (`instructeurID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

DROP TABLE IF EXISTS `Eend`.`beschikbaarheid` ;

CREATE TABLE IF NOT EXISTS `Eend`.`beschikbaarheid` (
  `beschikbaarheidID` INT(11) NOT NULL AUTO_INCREMENT,
  `instructeurID` INT(11) NOT NULL,
  `dagNaam` ENUM('Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Vrijdag', 'Zaterdag', 'Zondag') NOT NULL,
  `beginTijd` TIME NOT NULL,
  `eindTijd` TIME NOT NULL,
  `maxLessen` INT(11) NOT NULL DEFAULT 6,
  PRIMARY KEY (`beschikbaarheidID`),
  INDEX `fk_beschikbaar_instr` (`instructeurID` ASC) VISIBLE,
  CONSTRAINT `fk_beschikbaar_instr`
    FOREIGN KEY (`instructeurID`)
    REFERENCES `Eend`.`instructeurs` (`instructeurID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

DROP TABLE IF EXISTS `Eend`.`instructeur_auto` ;

CREATE TABLE IF NOT EXISTS `Eend`.`instructeur_auto` (
  `instructeurID` INT(11) NOT NULL,
  `autoID` INT(11) NOT NULL,
  PRIMARY KEY (`instructeurID`, `autoID`),
  INDEX `fk_instr_auto_auto` (`autoID` ASC) VISIBLE,
  CONSTRAINT `fk_instr_auto_auto`
    FOREIGN KEY (`autoID`)
    REFERENCES `Eend`.`Autos` (`autoID`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_instr_auto_instr`
    FOREIGN KEY (`instructeurID`)
    REFERENCES `Eend`.`instructeurs` (`instructeurID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

DROP TABLE IF EXISTS `Eend`.`lespakket` ;

CREATE TABLE IF NOT EXISTS `Eend`.`lespakket` (
  `idlespakket` INT(11) NOT NULL AUTO_INCREMENT,
  `naam` VARCHAR(255) NOT NULL,
  `uren` INT(11) NOT NULL,
  `prijs` DECIMAL(6,2) NOT NULL,
  PRIMARY KEY (`idlespakket`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

DROP TABLE IF EXISTS `Eend`.`studenten` ;

CREATE TABLE IF NOT EXISTS `Eend`.`studenten` (
  `studentID` INT(11) NOT NULL AUTO_INCREMENT,
  `voornaam` VARCHAR(50) NOT NULL,
  `tussenvoegsel` VARCHAR(30) NULL DEFAULT NULL,
  `achternaam` VARCHAR(100) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `wachtwoord` VARCHAR(255) NOT NULL,
  `telefoon` VARCHAR(20) NOT NULL,
  `beperking` TINYINT(4) NOT NULL,
  `omschrijving` VARCHAR(255) NULL DEFAULT NULL,
  `geboortedatum` DATE NOT NULL,
  `status` ENUM('pending', 'actief', 'geslaagd') NOT NULL,
  `transmissie` ENUM('schakel', 'automaat') NOT NULL DEFAULT 'schakel',
  `poging` INT(100) NULL,
  `geslaagd` TINYINT(1) NULL,
  PRIMARY KEY (`studentID`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

DROP TABLE IF EXISTS `Eend`.`lessen` ;

CREATE TABLE IF NOT EXISTS `Eend`.`lessen` (
  `lesID` INT(11) NOT NULL AUTO_INCREMENT,
  `lesDatum` DATE NOT NULL,
  `lestijd` TIME NOT NULL,
  `ophaalLocatie` VARCHAR(100) NOT NULL,
  `doel` VARCHAR(255) NOT NULL,
  `onderwerpen` VARCHAR(255) NOT NULL,
  `studentID` INT(11) NOT NULL,
  `instructeurID` INT(11) NOT NULL,
  `autoID` INT(11) NOT NULL,
  `vervallen` TINYINT(1) NOT NULL DEFAULT 0,
  `goedgekeurd` TINYINT(1) NULL DEFAULT NULL,
  `goedgekeurd_op` TIMESTAMP NULL DEFAULT NULL,
  `redenWijzig` VARCHAR(300) NULL DEFAULT NULL,
  `redenVervalt` VARCHAR(300) NULL DEFAULT NULL,
  PRIMARY KEY (`lesID`),
  INDEX `fk_lessen_studenten` (`studentID` ASC) VISIBLE,
  INDEX `fk_lessen_instructeurs` (`instructeurID` ASC) VISIBLE,
  INDEX `fk_lessen_autos` (`autoID` ASC) VISIBLE,
  CONSTRAINT `fk_lessen_autos`
    FOREIGN KEY (`autoID`)
    REFERENCES `Eend`.`Autos` (`autoID`),
  CONSTRAINT `fk_lessen_instructeurs`
    FOREIGN KEY (`instructeurID`)
    REFERENCES `Eend`.`instructeurs` (`instructeurID`),
  CONSTRAINT `fk_lessen_studenten`
    FOREIGN KEY (`studentID`)
    REFERENCES `Eend`.`studenten` (`studentID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

DROP TABLE IF EXISTS `Eend`.`meldingen` ;

CREATE TABLE IF NOT EXISTS `Eend`.`meldingen` (
  `meldingID` INT(11) NOT NULL AUTO_INCREMENT,
  `titel` VARCHAR(100) NOT NULL,
  `bericht` VARCHAR(500) NOT NULL,
  `ontvanger_type` ENUM('iedereen', 'alle_studenten', 'alle_instructeurs', 'student', 'instructeur', 'admin') NOT NULL,
  `ontvanger_id` INT(11) NULL DEFAULT NULL,
  `datum_gemaakt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`meldingID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

DROP TABLE IF EXISTS `Eend`.`student_lespakket` ;

CREATE TABLE IF NOT EXISTS `Eend`.`student_lespakket` (
  `studentID` INT(11) NULL DEFAULT NULL,
  `idlespakket` INT(11) NULL DEFAULT NULL,
  `overige_uren` INT(11) NULL DEFAULT NULL,
  `bedrag` DECIMAL(6,2) NULL,
  INDEX `fk_student_lespakket_student` (`studentID` ASC) VISIBLE,
  INDEX `fk_student_lespakket_pakket` (`idlespakket` ASC) VISIBLE,
  CONSTRAINT `fk_student_lespakket_pakket`
    FOREIGN KEY (`idlespakket`)
    REFERENCES `Eend`.`lespakket` (`idlespakket`),
  CONSTRAINT `fk_student_lespakket_student`
    FOREIGN KEY (`studentID`)
    REFERENCES `Eend`.`studenten` (`studentID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

DROP TABLE IF EXISTS `Eend`.`studenten_has_instructeurs` ;

CREATE TABLE IF NOT EXISTS `Eend`.`studenten_has_instructeurs` (
  `studentID` INT(11) NOT NULL,
  `instructeurID` INT(11) NOT NULL,
  PRIMARY KEY (`studentID`, `instructeurID`),
  INDEX `fk_student_instr_instr` (`instructeurID` ASC) VISIBLE,
  CONSTRAINT `fk_student_instr_instr`
    FOREIGN KEY (`instructeurID`)
    REFERENCES `Eend`.`instructeurs` (`instructeurID`),
  CONSTRAINT `fk_student_instr_student`
    FOREIGN KEY (`studentID`)
    REFERENCES `Eend`.`studenten` (`studentID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

DROP TABLE IF EXISTS `Eend`.`bijkopen` ;

CREATE TABLE IF NOT EXISTS `Eend`.`bijkopen` (
  `idbijkopen` INT NOT NULL AUTO_INCREMENT,
  `naam` VARCHAR(255) NOT NULL,
  `uren` INT(11) NOT NULL,
  `prijs` DECIMAL(6,2) NOT NULL,
  `studentID` INT(11) NOT NULL,
  PRIMARY KEY (`idbijkopen`),
  INDEX `fk_bijkopen_studenten1_idx` (`studentID` ASC) VISIBLE,
  CONSTRAINT `fk_bijkopen_studenten1`
    FOREIGN KEY (`studentID`)
    REFERENCES `Eend`.`studenten` (`studentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
